#!/usr/bin/env bash

mysql --user=root --password="$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_TEST;
    GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE_TEST%\`.* TO '$MYSQL_USER'@'%';
EOSQL
